services:
  - type: web
    name: judge0
    plan: free
    env: docker
    docker:
      dockerfile: Dockerfile
    healthCheckPath: /about
    envVars:
      - key: JUDGE0_DB_NAME
        value: judge0
      - key: JUDGE0_DB_PORT
        value: 5432
      - key: JUDGE0_SECRET_KEY
        generateValue: true
      - key: JUDGE0_SAVE_COMPILE_OUTPUT
        value: "true"
      - key: JUDGE0_ALLOW_ORIGIN
        value: "*"

  - type: redis
    name: judge0-redis
    plan: free
